### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-app#83]
- [x] During job editing https://github.com/topcoder-platform/taas-app/issues/12#issuecomment-775965604. Let's place the `status` field in read-only. Only BookingManager / Topcoder Admin can edit those fields.

- [x] "Edit Job Details" button (https://github.com/topcoder-platform/taas-app/issues/12) should be only visible to the users who can edit jobs:
   ![image](https://user-images.githubusercontent.com/146016/107849536-91349900-6e04-11eb-97ff-593a7fa37808.png)

   - also the edit job page should be only accessible for the same users, and return "Access Denied" to other users if we try to navigate to the Edit Job page by other users

- [x] "Edit Member Details" action:

   ![image](https://user-images.githubusercontent.com/146016/107849591-f8524d80-6e04-11eb-94e6-bdf2d78f70e9.png)
   
   and "Edit Member Details button 
   
   ![image](https://user-images.githubusercontent.com/146016/107849598-07d19680-6e05-11eb-92e8-b9c5725b9372.png)
   
   Should be only visible to BookingManager / Topcoder Admin users.
   
   - also the edit member details page should be only accessible for the same users, and return "Access Denied" to other users if we try to navigate to the Edit member details page by other users
   
- [x] "Member Rate" on the View/Edit Member Details page is shown to all the users. It should only be shown to Booking Manager and Topcoder Admins. For other users it should be hidden.

- [x] Hide Yes No buttons for Candidates list for user without access to update candidate status https://github.com/topcoder-platform/taas-app/issues/38

**Comment by maxceem** [comment]
At the moment 3 points out of 5 are ready for QA in this ticket.

**Comment by maxceem** [comment]
@sandhiyakavi this is fully ready for testing on DEV.

There is only one case that is not ready and it's logged as a separate issue https://github.com/topcoder-platform/taas-app/issues/112. I'm not sure if we could get it done for the `1.5` realease.

**Comment by sandhiyakavi** [comment]
@maxceem Below are some of the discrepancies found,

1. Connect Manager and users who are just member of the project(not created the job/project) are able to access the Edit Job page. Not able to edit though
<img width="960" alt="for_connectmanager_able toaccess" src="https://user-images.githubusercontent.com/55895538/108990211-e2cd0580-76d9-11eb-869f-f192cb0b721e.png">
<img width="960" alt="member_access_edit page" src="https://user-images.githubusercontent.com/55895538/108990227-e6608c80-76d9-11eb-8579-35d98d5f7283.png">

2. Similar issue with edit resource booking page.

![image](https://user-images.githubusercontent.com/55895538/108990595-6be43c80-76da-11eb-8e75-be8799787ac0.png)
![image](https://user-images.githubusercontent.com/55895538/108990676-874f4780-76da-11eb-8de0-9cee7389d960.png)

3. Also I am able to edit the job with the user who created the job. though Edit Job detail button is not visible. Is that happening for specific users?


https://user-images.githubusercontent.com/55895538/108994504-3857e100-76df-11eb-913b-cc2f3a1560b8.mp4



4. Also I am not getting the point why to hide member rate field in Edit resource bookings page if the page itself won't be visible for users other than BookingManager/Admin.(Though it's visible now).Please correct me if I am wrong.

**Comment by maxceem** [comment]
Thank you @sandhiyakavi 

1. and 2. good catch, I will fix it.

> 3. Also I am able to edit the job with the user who created the job. though Edit Job detail button is not visible. Is that happening for specific users?

At the moment we cannot show this button for the users who create jobs because of the API limitation. I've created a separate issue to track this https://github.com/topcoder-platform/taas-app/issues/112. It would be done after we create a new endpoint on API https://github.com/topcoder-platform/taas-apis/issues/154. Not sure if this could be done in this release though.

> 4. Also I am not getting the point why to hide member rate field in Edit resource bookings page if the page itself won't be visible for users other than BookingManager/Admin.(Though it's visible now).Please correct me if I am wrong.

This is just to make sure we would never accidently show it. Even if tomorrow we would let regular users to edit resource bookings, the member rate would be still hidden for them. As this is a separate requirement we have a separate permission that controls it, so we would not accidentally leak it.

**Comment by maxceem** [comment]
@sandhiyakavi regarding 1 and 2 it may take some time to fix it. But it looks for me that we might treat it as `enhancement` rather than a bug:
- user don't see links to access these pages
- even if user access this pages by the direct link, they cannot see there any secret data
- even is user tries to edit, they would get error form the server that they don't have permissions

So I suggest treat this issue as done, and I've logged a new issue to make this improvement https://github.com/topcoder-platform/taas-app/issues/117

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.Working as expected

**Comment by sandhiyakavi** [comment]
Fixed: 🆗 in Production via milestone v1.5

The Edit Job Details button and Edit Resource Booking Details button and Edit Resource booking links are not visible for a member of the project.

![image](https://user-images.githubusercontent.com/55895538/109262190-6e62a580-7844-11eb-8fbf-5972940ab138.png)
![image](https://user-images.githubusercontent.com/55895538/109262207-7884a400-7844-11eb-9c6b-58234a8e0a5b.png)
![image](https://user-images.githubusercontent.com/55895538/109262249-8f2afb00-7844-11eb-9f9b-4987a848ac34.png)

@lakshmiathreya Needs BookingManager, Admin and Manager role for checking the below features.

1. During job editing #12 (comment). Let's place the status field in read-only. Only BookingManager / Topcoder Admin can edit those fields. (In Job Editing page).
2.  Edit Job Details" button  visible to the Booking Manager and not to Connect Manager.
3. "Edit Member Details" action and "Edit Member Details" button only visible to  BookingManager / Topcoder Admin
4. "Member Rate" on the View/Edit Member Details page is shown to all the users. It should only be shown to Booking Manager and Topcoder Admins. For other users it should be hidden.
5. Hide Yes No buttons for Candidates list for user without access to update candidate status. Need to check for Connect Manager role.

**Comment by lakshmiathreya** [comment]
1. Job Editing by Admin and BM ... 
<img width="1680" alt="Screenshot 2021-02-26 at 3 44 14 PM" src="https://user-images.githubusercontent.com/51733042/109288122-77ef0c00-784a-11eb-81de-98260d07d856.png">
<img width="1680" alt="Screenshot 2021-02-26 at 3 50 32 PM" src="https://user-images.githubusercontent.com/51733042/109288131-7a516600-784a-11eb-8ba5-b98bfa47c35f.png">

**Comment by lakshmiathreya** [comment]
2. Connect manager not seeing Edit :
<img width="1680" alt="Screenshot 2021-02-26 at 3 54 49 PM" src="https://user-images.githubusercontent.com/51733042/109288569-095e7e00-784b-11eb-86c8-8ba6bee6e258.png">

**Comment by lakshmiathreya** [comment]
3. Member rate seen by Admin and BM:
<img width="1680" alt="Screenshot 2021-02-26 at 4 10 09 PM" src="https://user-images.githubusercontent.com/51733042/109290214-58a5ae00-784d-11eb-9baa-8f154b53d9a6.png">
<img width="1680" alt="Screenshot 2021-02-26 at 4 10 42 PM" src="https://user-images.githubusercontent.com/51733042/109290234-5cd1cb80-784d-11eb-9e51-f2963087681f.png">

**Comment by lakshmiathreya** [comment]
5. @sandhiyakavi pls attach a Dev screenshot for this as reference. I will verify Connect Mgr on Prod based on that.

**Comment by sandhiyakavi** [comment]
Review Candidates page for Connect Manageer in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/109292754-34a69480-786e-11eb-9c45-4471c0b8e8ac.png)

**Comment by lakshmiathreya** [comment]
Booking Manager - <img width="1680" alt="Screenshot 2021-02-27 at 11 48 39 AM" src="https://user-images.githubusercontent.com/51733042/109377500-e044f880-78f1-11eb-9a98-029d242289ed.png">

**Comment by lakshmiathreya** [comment]
Connect Manager - 
<img width="1680" alt="Screenshot 2021-02-27 at 11 50 33 AM" src="https://user-images.githubusercontent.com/51733042/109377547-14b8b480-78f2-11eb-8327-0bc8c3fa6870.png">

**Comment by lakshmiathreya** [comment]
Admin - 
<img width="1680" alt="Screenshot 2021-02-27 at 11 48 06 AM" src="https://user-images.githubusercontent.com/51733042/109377563-28641b00-78f2-11eb-813c-c818eaf8de52.png">

**Comment by lakshmiathreya** [comment]
5. Connect manager unable to see Yes/No in Review candidates. However, Admin/BM are also not able to see Yes/No. Will close this and add this Q to #38
